"""Generate an executable analysis script from a session's prep recipe.

Design choice (docs/DESIGN_project_file.md): the script REPLAYS the recorded
requests against a running uSTAT backend rather than translating each step
into pandas. Translation would be a second implementation of every operation,
and two implementations of `recode` is how a script and the GUI drift apart.
Replay reproduces exactly what the GUI did, through the same code, for every
op the recipe can contain -- undo/redo included, since the server replays its
own undo stack.

The script's shape:

    1. upload the ORIGINAL raw file (path supplied by the user at the top),
    2. replay every recorded step in order,
    3. export the prepared dataset,
    4. list every saved analysis with its parameters, as documentation --
       an analysis snapshot records its params but not its endpoint, so the
       honest output is the definition, not a guessed call.
"""
from __future__ import annotations

import json
import time
from urllib.parse import quote
from typing import Optional

from services.runtime_identity import runtime_identity

# op slug → (HTTP method, URL template). {sid} is filled at runtime by the
# script itself; other placeholders come from the step's params.
_ROUTES = {
    "sessions/edit_cell": ("PATCH", "/api/sessions/{sid}/cell"),
    "sessions/set_cells": ("POST", "/api/sessions/{sid}/set_cells"),
    "sessions/clear_cells": ("POST", "/api/sessions/{sid}/clear_cells"),
    "sessions/swap_value_labels": ("POST", "/api/sessions/{sid}/swap_value_labels"),
    "sessions/reorder_columns": ("POST", "/api/sessions/{sid}/reorder_columns"),
    "sessions/select_cases": ("POST", "/api/sessions/{sid}/select_cases"),
    "sessions/clear_cases": ("DELETE", "/api/sessions/{sid}/select_cases"),
    "sessions/delete_row": ("DELETE", "/api/sessions/{sid}/row/{row_index}"),
    "sessions/undo": ("POST", "/api/sessions/{sid}/undo"),
    "sessions/redo": ("POST", "/api/sessions/{sid}/redo"),
    "merge/apply": ("POST", "/api/merge/apply"),
    "filter": ("POST", "/api/sessions/{sid}/select_cases"),
}


def _route_for(op: str, params: dict):
    if op in _ROUTES:
        method, url = _ROUTES[op]
        if op == "sessions/delete_row":
            url = url.replace("{row_index}", str(params.get("row_index", 0)))
            params = {k: v for k, v in params.items() if k != "row_index"}
        if op == "filter":
            params = {"conditions": params.get("conditions", []), "apply": True}
        return method, url, params
    if op == "compute/delete_column":
        column = quote(str(params.get("column", "")), safe="")
        return "DELETE", f"/api/compute/{{sid}}/column/{column}", {}
    if op.startswith("compute/"):
        return "POST", f"/api/compute/{{sid}}/{op.split('/', 1)[1]}", params
    return None


def _py(value) -> str:
    """A JSON-safe value as Python source (json is a Python subset here,
    modulo the constants)."""
    return (
        json.dumps(value, ensure_ascii=False, indent=4)
        .replace(": true", ": True")
        .replace(": false", ": False")
        .replace(": null", ": None")
    )


def generate_python_script(
    steps: list,
    analyses: Optional[list] = None,
    project_name: str = "project",
) -> str:
    """A runnable Python replay script for the recipe, as source text."""
    identity = runtime_identity()
    packages = ", ".join(f"{k} {v}" for k, v in (identity.get("packages") or {}).items())
    import_step = next((s for s in steps if s.get("op") == "import"), None)
    raw_name = (import_step or {}).get("params", {}).get("filename") or "your_raw_file.csv"

    lines: list[str] = [
        "#!/usr/bin/env python3",
        '"""Replay script generated by uSTAT.',
        "",
        f"Project: {project_name}",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Engine at generation time: python {identity.get('python')} ({packages})",
        "",
        "Reproduces the recorded data preparation by replaying it against a",
        "running uSTAT backend -- the same code path the GUI used, so the",
        "prepared dataset is identical by construction, not by translation.",
        "Compare package versions above with your server's /api/engine/identity",
        "before attributing any numeric difference to the data.",
        '"""',
        "import requests",
        "",
        'BASE = "http://localhost:8000"  # your running uSTAT backend',
        f'RAW_FILE = "{raw_name}"  # path to the ORIGINAL imported file',
        'OUT_FILE = "prepared.csv"',
        "",
        "",
        "def check(r):",
        "    if r.status_code >= 300:",
        '        raise SystemExit(f"step failed ({r.status_code}): {r.text[:300]}")',
        "    return r",
        "",
        "",
        "# 1. Import the raw file exactly as the GUI did.",
        'with open(RAW_FILE, "rb") as fh:',
        '    r = check(requests.post(f"{BASE}/api/upload/", files={"file": (RAW_FILE, fh)}))',
        'sid = r.json()["session_id"]',
        'print(f"imported {RAW_FILE} as session {sid}")',
        "",
    ]

    replayable = [s for s in steps if s.get("op") != "import"]
    if replayable:
        lines.append("# 2. Replay the recorded preparation steps, in order.")
    skipped: list[str] = []
    for i, step in enumerate(replayable, start=1):
        op = str(step.get("op", ""))
        params = dict(step.get("params") or {})
        route = _route_for(op, params)
        if route is None:
            skipped.append(op)
            lines += [f"# step {i}: {op} -- no replay route known; apply manually:",
                      f"# params: {json.dumps(params, ensure_ascii=False)}", ""]
            continue
        method, url, body = route
        lines.append(f"# step {i}: {op}")
        call = f'requests.{method.lower()}(f"{{BASE}}{url}"'
        if body:
            lines.append(f"body = {_py(body)}")
            call += ", json=body"
        call += ")"
        lines.append(f"check({call})")
        lines.append("")

    lines += [
        "# 3. Export the prepared dataset.",
        'r = check(requests.get(f"{BASE}/api/sessions/{sid}/export/csv"))',
        'with open(OUT_FILE, "wb") as fh:',
        "    fh.write(r.content)",
        'print(f"prepared dataset written to {OUT_FILE}")',
    ]

    if analyses:
        lines += [
            "",
            "# 4. Saved analyses (definitions).",
            "# A saved analysis records its panel and parameters; re-running it",
            "# is done in uSTAT (restore + Run). The definitions are listed so",
            "# the analysis is specified, not merely remembered:",
        ]
        for a in analyses:
            if not isinstance(a, dict):
                continue
            lines.append(f"#   - {a.get('name')} (panel: {a.get('panel')})")
            stamp = (a.get("snapshot") or {}).get("stamp") if isinstance(a.get("snapshot"), dict) else None
            params_key = (stamp or {}).get("paramsKey")
            if isinstance(params_key, str) and params_key not in ("", "null"):
                lines.append(f"#     params: {params_key}")

    if skipped:
        lines += ["", f"# NOTE: {len(skipped)} step(s) had no replay route and are marked above."]

    return "\n".join(lines) + "\n"
