"""jamovi-style syntax mode: a saved analysis's definition as Python/R code.

Different job from script_export.py. The replay script reproduces results
exactly by driving uSTAT's own API; this module shows what the analysis IS in
the reader's own language: the scipy/statsmodels call, the R formula. It is a
teaching and methods-section view, not a reproduction guarantee, and it says
so in its header comment: uSTAT's implementation may differ in defaults
(handling of ties, variance equality fallbacks, reference coding), so the
per-result provenance line remains the authority on what produced a number.

Coverage is an explicit allow-list. An analysis outside it gets None, and the
caller shows "no translation yet" with the raw params -- an honest gap beats
a wrong formula. Params come from the panel's own runParams object
(frontend), field names as the panels send them.
"""
from __future__ import annotations

from typing import Optional

_HEADER_PY = (
    "# {title}\n"
    "# Generated by uSTAT syntax view. df = the prepared dataset\n"
    "# (see the replay script; prepared.csv loads with pd.read_csv).\n"
    "# uSTAT's own implementation may differ in defaults; the result's\n"
    "# provenance line says what actually computed your number.\n"
)
_HEADER_R = (
    "# {title}\n"
    "# Generated by uSTAT syntax view. df = the prepared dataset\n"
    "# (see the replay script; prepared.csv loads with read.csv).\n"
    "# uSTAT's own implementation may differ in defaults; the result's\n"
    "# provenance line says what actually computed your number.\n"
)


def _fml(outcome: str, predictors: list) -> str:
    return f"{outcome} ~ {' + '.join(predictors) if predictors else '1'}"


def _hypothesis(params: dict) -> Optional[dict]:
    test = params.get("test")
    col = params.get("col") or "outcome"
    group = params.get("groupCol") or "group"
    mu = params.get("mu", 0)

    if test == "ttest_1sample":
        return {
            "title": f"One-sample t-test: {col} vs mu = {mu}",
            "python": (
                "from scipy import stats\n\n"
                f'stats.ttest_1samp(df["{col}"].dropna(), popmean={mu})'
            ),
            "r": f't.test(df${col}, mu = {mu})',
        }
    if test == "ttest_2sample":
        return {
            "title": f"Independent t-test: {col} by {group}",
            "python": (
                "from scipy import stats\n\n"
                f'groups = [g["{col}"].dropna() for _, g in df.groupby("{group}")]\n'
                "# uSTAT checks Levene's test and falls back to Welch when\n"
                "# variances differ; equal_var=False reproduces the Welch case.\n"
                "stats.ttest_ind(*groups, equal_var=False)"
            ),
            "r": (
                "# uSTAT checks Levene's test and falls back to Welch when\n"
                "# variances differ; var.equal = FALSE is the Welch case.\n"
                f"t.test({col} ~ {group}, data = df, var.equal = FALSE)"
            ),
        }
    if test == "anova":
        return {
            "title": f"One-way ANOVA: {col} by {group}",
            "python": (
                "import statsmodels.api as sm\n"
                "from statsmodels.formula.api import ols\n\n"
                f'fit = ols("{col} ~ C({group})", data=df).fit()\n'
                "sm.stats.anova_lm(fit, typ=2)"
            ),
            "r": f"summary(aov({col} ~ factor({group}), data = df))",
        }
    if test == "mannwhitney":
        return {
            "title": f"Mann-Whitney U: {col} by {group}",
            "python": (
                "from scipy import stats\n\n"
                f'a, b = [g["{col}"].dropna() for _, g in df.groupby("{group}")]\n'
                "stats.mannwhitneyu(a, b, alternative=\"two-sided\")"
            ),
            "r": f"wilcox.test({col} ~ {group}, data = df)",
        }
    if test == "kruskal":
        return {
            "title": f"Kruskal-Wallis: {col} by {group}",
            "python": (
                "from scipy import stats\n\n"
                f'groups = [g["{col}"].dropna() for _, g in df.groupby("{group}")]\n'
                "stats.kruskal(*groups)"
            ),
            "r": f"kruskal.test({col} ~ factor({group}), data = df)",
        }
    if test == "ancova":
        covariates = list(params.get("covariates") or [])
        rhs = f"C({group})" + "".join(f" + {c}" for c in covariates)
        r_rhs = f"factor({group})" + "".join(f" + {c}" for c in covariates)
        return {
            "title": f"ANCOVA: {col} by {group}, adjusted for {', '.join(covariates) or 'nothing'}",
            "python": (
                "from statsmodels.formula.api import ols\n"
                "from statsmodels.stats.anova import anova_lm\n\n"
                "# Same model uSTAT fits: group + covariates, Type II SS.\n"
                f'fit = ols("{col} ~ {rhs}", data=df).fit()\n'
                "anova_lm(fit, typ=2)"
            ),
            "r": (
                "library(car)\n"
                f"fit <- lm({col} ~ {r_rhs}, data = df)\n"
                "Anova(fit, type = 2)"
            ),
        }
    if test == "two_way":
        factor2 = params.get("factor2") or "factor2"
        return {
            "title": f"Two-way ANOVA: {col} by {group} x {factor2}",
            "python": (
                "from statsmodels.formula.api import ols\n"
                "from statsmodels.stats.anova import anova_lm\n\n"
                "# Full factorial, as uSTAT fits it: main effects + interaction.\n"
                f'fit = ols("{col} ~ C({group}) * C({factor2})", data=df).fit()\n'
                "anova_lm(fit, typ=2)"
            ),
            "r": (
                "library(car)\n"
                f"fit <- lm({col} ~ factor({group}) * factor({factor2}), data = df)\n"
                "Anova(fit, type = 2)"
            ),
        }
    if test in ("chisquare", "fisher"):
        col2 = params.get("col2") or params.get("groupCol") or "group"
        fn_py = "chi2_contingency(tab)" if test == "chisquare" else "fisher_exact(tab)"
        fn_r = "chisq.test(tab)" if test == "chisquare" else "fisher.test(tab)"
        return {
            "title": f"{'Chi-square' if test == 'chisquare' else 'Fisher exact'}: {col} x {col2}",
            "python": (
                "from scipy.stats import chi2_contingency, fisher_exact\n"
                "import pandas as pd\n\n"
                f'tab = pd.crosstab(df["{col}"], df["{col2}"])\n'
                f"{fn_py}"
            ),
            "r": f"tab <- table(df${col}, df${col2})\n{fn_r}",
        }
    return None


def _models(params: dict) -> Optional[dict]:
    model = params.get("model")
    outcome = params.get("outcome") or "outcome"
    predictors = list(params.get("predictors") or [])

    if model == "linear":
        return {
            "title": f"Linear regression: {_fml(outcome, predictors)}",
            "python": (
                "import statsmodels.formula.api as smf\n\n"
                f'fit = smf.ols("{_fml(outcome, predictors)}", data=df).fit()\n'
                "fit.summary()"
            ),
            "r": f"fit <- lm({_fml(outcome, predictors)}, data = df)\nsummary(fit)\nconfint(fit)",
        }
    if model == "logistic":
        return {
            "title": f"Logistic regression: {_fml(outcome, predictors)}",
            "python": (
                "import numpy as np\n"
                "import statsmodels.formula.api as smf\n\n"
                f'fit = smf.logit("{_fml(outcome, predictors)}", data=df).fit()\n'
                "np.exp(fit.params)  # odds ratios\n"
                "np.exp(fit.conf_int())  # their 95% CIs"
            ),
            "r": (
                f"fit <- glm({_fml(outcome, predictors)}, data = df, family = binomial)\n"
                "exp(cbind(OR = coef(fit), confint(fit)))"
            ),
        }
    if model == "poisson":
        return {
            "title": f"Poisson regression: {_fml(outcome, predictors)}",
            "python": (
                "import statsmodels.formula.api as smf\n"
                "import statsmodels.api as sm\n\n"
                f'fit = smf.glm("{_fml(outcome, predictors)}", data=df,\n'
                "              family=sm.families.Poisson()).fit()\n"
                "fit.summary()"
            ),
            "r": f"fit <- glm({_fml(outcome, predictors)}, data = df, family = poisson)\nsummary(fit)",
        }
    if model == "cox":
        duration = params.get("durationCol") or "time"
        event = params.get("eventCol") or "event"
        rhs = " + ".join(predictors) if predictors else "1"
        return {
            "title": f"Cox proportional hazards: Surv({duration}, {event}) ~ {rhs}",
            "python": (
                "from lifelines import CoxPHFitter\n\n"
                "cph = CoxPHFitter()\n"
                f'cph.fit(df[["{duration}", "{event}"' +
                "".join(f', "{p}"' for p in predictors) + "]],\n"
                f'        duration_col="{duration}", event_col="{event}")\n'
                "cph.print_summary()"
            ),
            "r": (
                "library(survival)\n"
                f"fit <- coxph(Surv({duration}, {event}) ~ {rhs}, data = df)\n"
                "summary(fit)"
            ),
        }
    return None


_PANELS = {
    "hypothesis": _hypothesis,
    "models": _models,
}


def translate(panel: str, params: dict) -> Optional[dict]:
    """{title, python, r} for a known (panel, params) combination, else None."""
    handler = _PANELS.get(panel)
    if handler is None:
        return None
    out = handler(params if isinstance(params, dict) else {})
    if out is None:
        return None
    return {
        "title": out["title"],
        "python": _HEADER_PY.format(title=out["title"]) + out["python"] + "\n",
        "r": _HEADER_R.format(title=out["title"]) + out["r"] + "\n",
    }
