"""jamovi-style syntax mode: a saved analysis's definition as Python/R code.

Different job from script_export.py. The replay script reproduces results
exactly by driving uSTAT's own API; this module shows what the analysis IS in
the reader's own language: the scipy/statsmodels call, the R formula. It is a
teaching and methods-section view, not a reproduction guarantee, and it says
so in its header comment: uSTAT's implementation may differ in defaults
(handling of ties, variance equality fallbacks, reference coding), so the
per-result provenance line remains the authority on what produced a number.

Coverage is an explicit allow-list. An analysis outside it gets None, and the
caller shows "no translation yet" with the raw params -- an honest gap beats
a wrong formula.

Two inputs, tried in this order:

* the request the result was computed from (method, URL, JSON body), which a
  result's stamp records when the panel shows the response as returned. It is
  keyed by endpoint, uses the API's own field names, and is what the server
  actually received, so it is preferred. The per-endpoint templates live in
  services/syntax/, one module per family;
* the panel's own runParams object (frontend field names), for analyses saved
  without a recorded request.
"""
from __future__ import annotations

import re
from typing import Callable, Dict, Optional
from urllib.parse import parse_qs, urlsplit

from services.syntax import ENDPOINTS

_HEADER_PY = (
    "# {title}\n"
    "# Generated by uSTAT syntax view. df = the prepared dataset\n"
    "# (see the replay script; prepared.csv loads with pd.read_csv).\n"
    "# uSTAT's own implementation may differ in defaults; the result's\n"
    "# provenance line says what actually computed your number.\n"
)
_HEADER_R = (
    "# {title}\n"
    "# Generated by uSTAT syntax view. df = the prepared dataset\n"
    "# (see the replay script; prepared.csv loads with read.csv).\n"
    "# uSTAT's own implementation may differ in defaults; the result's\n"
    "# provenance line says what actually computed your number.\n"
)


def _fml(outcome: str, predictors: list) -> str:
    return f"{outcome} ~ {' + '.join(predictors) if predictors else '1'}"


def _hypothesis(params: dict) -> Optional[dict]:
    test = params.get("test")
    col = params.get("col") or "outcome"
    group = params.get("groupCol") or "group"
    mu = params.get("mu", 0)

    if test == "ttest_1sample":
        return {
            "title": f"One-sample t-test: {col} vs mu = {mu}",
            "python": (
                "from scipy import stats\n\n"
                f'stats.ttest_1samp(df["{col}"].dropna(), popmean={mu})'
            ),
            "r": f't.test(df${col}, mu = {mu})',
        }
    if test == "ttest_2sample":
        return {
            "title": f"Independent t-test: {col} by {group}",
            "python": (
                "from scipy import stats\n\n"
                f'groups = [g["{col}"].dropna() for _, g in df.groupby("{group}")]\n'
                "# uSTAT checks Levene's test and falls back to Welch when\n"
                "# variances differ; equal_var=False reproduces the Welch case.\n"
                "stats.ttest_ind(*groups, equal_var=False)"
            ),
            "r": (
                "# uSTAT checks Levene's test and falls back to Welch when\n"
                "# variances differ; var.equal = FALSE is the Welch case.\n"
                f"t.test({col} ~ {group}, data = df, var.equal = FALSE)"
            ),
        }
    if test == "anova":
        return {
            "title": f"One-way ANOVA: {col} by {group}",
            "python": (
                "import statsmodels.api as sm\n"
                "from statsmodels.formula.api import ols\n\n"
                f'fit = ols("{col} ~ C({group})", data=df).fit()\n'
                "sm.stats.anova_lm(fit, typ=2)"
            ),
            "r": f"summary(aov({col} ~ factor({group}), data = df))",
        }
    if test == "mannwhitney":
        return {
            "title": f"Mann-Whitney U: {col} by {group}",
            "python": (
                "from scipy import stats\n\n"
                f'a, b = [g["{col}"].dropna() for _, g in df.groupby("{group}")]\n'
                "stats.mannwhitneyu(a, b, alternative=\"two-sided\")"
            ),
            "r": f"wilcox.test({col} ~ {group}, data = df)",
        }
    if test == "kruskal":
        return {
            "title": f"Kruskal-Wallis: {col} by {group}",
            "python": (
                "from scipy import stats\n\n"
                f'groups = [g["{col}"].dropna() for _, g in df.groupby("{group}")]\n'
                "stats.kruskal(*groups)"
            ),
            "r": f"kruskal.test({col} ~ factor({group}), data = df)",
        }
    if test == "ancova":
        covariates = list(params.get("covariates") or [])
        rhs = f"C({group})" + "".join(f" + {c}" for c in covariates)
        r_rhs = f"factor({group})" + "".join(f" + {c}" for c in covariates)
        return {
            "title": f"ANCOVA: {col} by {group}, adjusted for {', '.join(covariates) or 'nothing'}",
            "python": (
                "from statsmodels.formula.api import ols\n"
                "from statsmodels.stats.anova import anova_lm\n\n"
                "# Same model uSTAT fits: group + covariates, Type II SS.\n"
                f'fit = ols("{col} ~ {rhs}", data=df).fit()\n'
                "anova_lm(fit, typ=2)"
            ),
            "r": (
                "library(car)\n"
                f"fit <- lm({col} ~ {r_rhs}, data = df)\n"
                "Anova(fit, type = 2)"
            ),
        }
    if test == "two_way":
        factor2 = params.get("factor2") or "factor2"
        return {
            "title": f"Two-way ANOVA: {col} by {group} x {factor2}",
            "python": (
                "from statsmodels.formula.api import ols\n"
                "from statsmodels.stats.anova import anova_lm\n\n"
                "# Full factorial, as uSTAT fits it: main effects + interaction.\n"
                f'fit = ols("{col} ~ C({group}) * C({factor2})", data=df).fit()\n'
                "anova_lm(fit, typ=2)"
            ),
            "r": (
                "library(car)\n"
                f"fit <- lm({col} ~ factor({group}) * factor({factor2}), data = df)\n"
                "Anova(fit, type = 2)"
            ),
        }
    if test in ("chisquare", "fisher"):
        col2 = params.get("col2") or params.get("groupCol") or "group"
        fn_py = "chi2_contingency(tab)" if test == "chisquare" else "fisher_exact(tab)"
        fn_r = "chisq.test(tab)" if test == "chisquare" else "fisher.test(tab)"
        return {
            "title": f"{'Chi-square' if test == 'chisquare' else 'Fisher exact'}: {col} x {col2}",
            "python": (
                "from scipy.stats import chi2_contingency, fisher_exact\n"
                "import pandas as pd\n\n"
                f'tab = pd.crosstab(df["{col}"], df["{col2}"])\n'
                f"{fn_py}"
            ),
            "r": f"tab <- table(df${col}, df${col2})\n{fn_r}",
        }
    return None


def _models(params: dict) -> Optional[dict]:
    model = params.get("model")
    outcome = params.get("outcome") or "outcome"
    predictors = list(params.get("predictors") or [])

    if model == "linear":
        return {
            "title": f"Linear regression: {_fml(outcome, predictors)}",
            "python": (
                "import statsmodels.formula.api as smf\n\n"
                f'fit = smf.ols("{_fml(outcome, predictors)}", data=df).fit()\n'
                "fit.summary()"
            ),
            "r": f"fit <- lm({_fml(outcome, predictors)}, data = df)\nsummary(fit)\nconfint(fit)",
        }
    if model == "logistic":
        return {
            "title": f"Logistic regression: {_fml(outcome, predictors)}",
            "python": (
                "import numpy as np\n"
                "import statsmodels.formula.api as smf\n\n"
                f'fit = smf.logit("{_fml(outcome, predictors)}", data=df).fit()\n'
                "np.exp(fit.params)  # odds ratios\n"
                "np.exp(fit.conf_int())  # their 95% CIs"
            ),
            "r": (
                f"fit <- glm({_fml(outcome, predictors)}, data = df, family = binomial)\n"
                "# Wald intervals, as uSTAT (and statsmodels); confint() would profile.\n"
                "exp(cbind(OR = coef(fit), confint.default(fit)))"
            ),
        }
    if model == "poisson":
        return {
            "title": f"Poisson regression: {_fml(outcome, predictors)}",
            "python": (
                "import statsmodels.formula.api as smf\n"
                "import statsmodels.api as sm\n\n"
                f'fit = smf.glm("{_fml(outcome, predictors)}", data=df,\n'
                "              family=sm.families.Poisson()).fit()\n"
                "fit.summary()"
            ),
            "r": f"fit <- glm({_fml(outcome, predictors)}, data = df, family = poisson)\nsummary(fit)",
        }
    if model == "cox":
        duration = params.get("durationCol") or "time"
        event = params.get("eventCol") or "event"
        rhs = " + ".join(predictors) if predictors else "1"
        return {
            "title": f"Cox proportional hazards: Surv({duration}, {event}) ~ {rhs}",
            "python": (
                "from lifelines import CoxPHFitter\n\n"
                "cph = CoxPHFitter()\n"
                f'cph.fit(df[["{duration}", "{event}"' +
                "".join(f', "{p}"' for p in predictors) + "]],\n"
                f'        duration_col="{duration}", event_col="{event}")\n'
                "cph.print_summary()"
            ),
            "r": (
                "library(survival)\n"
                f"fit <- coxph(Surv({duration}, {event}) ~ {rhs}, data = df)\n"
                "summary(fit)"
            ),
        }
    return None


_PANELS = {
    "hypothesis": _hypothesis,
    "models": _models,
}


# ── Endpoint templates (recorded requests) ──────────────────────────────────
# Each handler takes the JSON body (plus query-string values merged in for
# GET endpoints) with the API's own field names. They live in
# services/syntax/, one module per family of analyses.

_ENDPOINTS: Dict[str, Callable[[dict], Optional[dict]]] = ENDPOINTS

_SID_SEGMENT = re.compile(r"/(\{sid\}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?=/|$)")


def _endpoint_key(url: str) -> str:
    """The path with any session segment normalised to {sid}."""
    return _SID_SEGMENT.sub("/{sid}", urlsplit(url).path).rstrip("/")


def translate_request(request: Optional[dict]) -> Optional[dict]:
    """{title, python, r} for a recorded request, else None."""
    if not isinstance(request, dict) or not isinstance(request.get("url"), str):
        return None
    handler = _ENDPOINTS.get(_endpoint_key(request["url"]))
    if handler is None:
        return None
    body = dict(request.get("body") or {}) if isinstance(request.get("body"), dict) else {}
    for key, values in parse_qs(urlsplit(request["url"]).query).items():
        body.setdefault(key, values[0] if len(values) == 1 else values)
    return handler(body)


def _wrap(out: Optional[dict]) -> Optional[dict]:
    if out is None:
        return None
    # The title is built from column names and sits in a comment line; a
    # line break inside one would push the rest out as code.
    title = " ".join(str(out["title"]).split())
    return {
        "title": title,
        "python": _HEADER_PY.format(title=title) + out["python"] + "\n",
        "r": _HEADER_R.format(title=title) + out["r"] + "\n",
    }


def translate(panel: str, params: dict, request: Optional[dict] = None) -> Optional[dict]:
    """{title, python, r} for a recorded request, or failing that a known
    (panel, params) combination; None when neither is covered."""
    from_request = _wrap(translate_request(request))
    if from_request is not None:
        return from_request
    handler = _PANELS.get(panel)
    if handler is None:
        return None
    return _wrap(handler(params if isinstance(params, dict) else {}))
