"""The frame envelope: what the browser is handed instead of the DataFrame.

Two things have to hold for this to be safe. First, `frame_from_envelope` has to
reproduce exactly what `store.get_filtered` would have handed a server-side
analysis -- same rows, same NAs, same level order, same reference category --
because the whole promise is that a local run and a server run answer the same
question. Second, none of that may depend on a pandas dtype: a column's kind is
declared, and a blank numeric column is `object` until someone types in it.

The dataset here is `qa/models_audit/dataset.csv`: 300 synthetic seeded rows
generated by `qa/models_audit/generate_dataset.py`, not patient data.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from pandas.testing import assert_frame_equal

from conftest import make_session
from services import store
from ustat_engine import EngineError
from ustat_engine.frame.envelope import (
    SCHEMA,
    build_envelope,
    filter_fingerprint,
    frame_from_envelope,
)
from ustat_engine.frame.levels import level_key, sorted_groups

DATASET = Path(__file__).resolve().parents[2] / "qa" / "models_audit" / "dataset.csv"


# ── helpers ───────────────────────────────────────────────────────────────────

def _upload(client) -> str:
    with open(DATASET, "rb") as fh:
        r = client.post(
            "/api/upload/", files={"file": ("dataset.csv", fh, "text/csv")}
        )
    assert r.status_code == 200, r.text
    return r.json()["session_id"]


def _kinds_like_the_router(session_id: str, df: pd.DataFrame) -> dict:
    from routers.upload import _detect_kind

    overrides = store.get_kind_overrides(session_id)
    return {c: (overrides.get(c) or _detect_kind(df[c])) for c in df.columns}


def _envelope_for(session_id: str, columns=None) -> dict:
    df = store.get(session_id)
    return build_envelope(
        df,
        kinds=_kinds_like_the_router(session_id, df),
        metadata=store.get_metadata(session_id),
        decimals=store.get_decimals(session_id),
        conditions=store.get_filter(session_id),
        columns=columns,
    )


def _normalise(df: pd.DataFrame, kinds: dict) -> pd.DataFrame:
    """Cast a frame to what its declared kinds say it holds.

    Applied to BOTH sides of the comparison. The store's frame is typed by
    whatever the CSV reader guessed (int64 for a column of whole numbers); the
    envelope is typed by the declared kind. Comparing them raw would test the
    CSV reader, not the envelope.
    """
    out = pd.DataFrame(index=df.index)
    for col in df.columns:
        kind = kinds[col]
        if kind == "numeric":
            out[col] = pd.to_numeric(df[col], errors="coerce").astype("float64")
        elif kind in ("categorical", "ordinal"):
            out[col] = [
                None if pd.isna(v) else level_key(v)
                for v in (df[col].astype(object) if str(df[col].dtype) == "category" else df[col])
            ]
        else:
            out[col] = [None if pd.isna(v) else str(v) for v in df[col]]
    return out


FILTER = [{"column": "arm", "operator": "eq", "value": "treat", "join": "AND"}]


# ── (a) the envelope reproduces the filtered frame ────────────────────────────

def test_envelope_round_trips_the_filtered_frame(client):
    sid = _upload(client)
    applied = client.post(
        f"/api/sessions/{sid}/select_cases", json={"conditions": FILTER, "apply": True}
    )
    assert applied.status_code == 200, applied.text
    assert 0 < applied.json()["selected"] < applied.json()["total"], (
        "the filter must actually drop rows or this test proves nothing"
    )

    unfiltered = store.get(sid)
    expected = store.get_filtered(sid)
    kinds = _kinds_like_the_router(sid, unfiltered)

    env = _envelope_for(sid)
    rebuilt = frame_from_envelope(env)

    assert env["schema"] == SCHEMA
    assert env["rows"] == len(expected) == len(rebuilt)

    # row_index is a POSITION in the unfiltered frame, not an index label.
    positions = [
        int(i) for i, label in enumerate(unfiltered.index) if label in set(expected.index)
    ]
    assert env["row_index"] == positions

    # Declared kind drives dtype, both ways.
    for spec in env["columns"]:
        col, kind = spec["name"], spec["kind"]
        dtype = str(rebuilt[col].dtype)
        if kind == "numeric":
            assert dtype == "float64", f"{col} is declared numeric but came back {dtype}"
        elif kind in ("categorical", "ordinal"):
            assert dtype == "category", f"{col} is declared {kind} but came back {dtype}"
        elif kind == "date":
            assert "datetime" in dtype
        else:
            assert dtype == "object"

    # NA positions survive per column.
    for col in expected.columns:
        want = expected[col].isna().to_numpy()
        got = rebuilt[col].isna().to_numpy()
        assert (want == got).all(), f"{col}: missing values landed in different rows"

    # Level order is the app's presentation order, and `reference` is the level
    # get_dummies(drop_first=True) actually drops.
    for spec in env["columns"]:
        if spec["storage"] != "cat":
            continue
        col = spec["name"]
        assert spec["levels"] == [level_key(v) for v in sorted_groups(expected[col])]
        dummies = pd.get_dummies(expected[col].dropna(), drop_first=True)
        dropped = [
            lv for lv in spec["model_levels"] if lv not in [level_key(c) for c in dummies.columns]
        ]
        assert dropped == [spec["reference"]]

    assert_frame_equal(
        _normalise(rebuilt, kinds),
        _normalise(expected.set_axis(rebuilt.index), kinds),
        check_dtype=False,
    )


def test_the_fingerprint_is_the_canonical_json_of_the_conditions():
    canonical = json.dumps(FILTER, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    assert filter_fingerprint(FILTER) == hashlib.sha256(canonical.encode()).hexdigest()
    # Key order in the caller's dict must not change the answer.
    reordered = [{k: v for k, v in reversed(list(FILTER[0].items()))}]
    assert filter_fingerprint(reordered) == filter_fingerprint(FILTER)


def test_columns_argument_narrows_the_transfer(client):
    sid = _upload(client)
    env = _envelope_for(sid, columns=["age", "arm"])
    assert [c["name"] for c in env["columns"]] == ["age", "arm"]
    assert set(env["data"]) == {"age", "arm"}


# ── (b) awkward names, awkward alphabets, blank numeric columns ───────────────

def _turkish_session() -> str:
    df = pd.DataFrame({
        "Evre Grubu": ["Açık", "Işıklı", "Şişme", "ığdır", "Açık", None],
        "Yaş (yıl)": [61, 47, 55, 39, 72, 68],
        "Boş Sütun": [None] * 6,
    })
    sid = make_session(df, "tframe_turkish")
    store.save_kind_overrides(sid, {"Boş Sütun": "numeric"})
    store.save_kind_overrides(sid, {"Evre Grubu": "categorical"})
    store.save_kind_overrides(sid, {"Yaş (yıl)": "numeric"})
    return sid


def test_column_names_and_turkish_levels_survive_verbatim():
    sid = _turkish_session()
    df = store.get(sid)
    env = build_envelope(
        df,
        kinds=_kinds_like_the_router(sid, df),
        metadata={},
        decimals={},
        conditions=[],
    )
    names = [c["name"] for c in env["columns"]]
    assert names == ["Evre Grubu", "Yaş (yıl)", "Boş Sütun"]

    rebuilt = frame_from_envelope(env)
    assert list(rebuilt.columns) == names
    for name in names:
        assert name in rebuilt  # byte-for-byte: spaces, parens, ı/ş/ğ intact

    # A blank column declared numeric is float64 NaN, not object None. Anything
    # that branched on dtype here would have called it text.
    assert str(rebuilt["Boş Sütun"].dtype) == "float64"
    assert rebuilt["Boş Sütun"].isna().all()

    # Turkish levels order by code point (Python's `sorted(key=str)`), not by
    # any locale collation: 'I' < 'Ş' < 'A-with-cedilla…' is a locale's answer,
    # not ours, and a locale-dependent order would differ between the server's
    # container and the user's browser.
    levels = next(c for c in env["columns"] if c["name"] == "Evre Grubu")["levels"]
    assert levels == sorted(["Açık", "Işıklı", "Şişme", "ığdır"], key=str)
    # 'A'(U+0041) < 'I'(U+0049) < 'ı'(U+0131) < 'Ş'(U+015E). A Turkish locale
    # would sort 'ı' next to 'i' and 'Ş' next to 'S' and give a different list.
    assert levels == ["Açık", "Işıklı", "ığdır", "Şişme"]
    assert rebuilt["Evre Grubu"].isna().sum() == 1

    store.delete(sid)


def test_ordinal_columns_come_back_ordered():
    df = pd.DataFrame({"grade": ["1", "2", "3", "2"]})
    sid = make_session(df, "tframe_ordinal")
    store.save_kind_overrides(sid, {"grade": "ordinal"})
    env = build_envelope(store.get(sid), kinds={"grade": "ordinal"}, conditions=[])
    spec = env["columns"][0]
    assert spec["storage"] == "cat" and spec["ordered"] is True
    rebuilt = frame_from_envelope(env)
    assert rebuilt["grade"].cat.ordered is True
    assert list(rebuilt["grade"].cat.categories) == ["1", "2", "3"]
    store.delete(sid)


# ── (c) the endpoint ─────────────────────────────────────────────────────────

def test_frame_endpoint_serves_the_envelope(client):
    sid = _upload(client)
    client.post(f"/api/sessions/{sid}/select_cases", json={"conditions": FILTER, "apply": True})

    r = client.get(f"/api/sessions/{sid}/frame")
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["schema"] == SCHEMA
    assert body["filter"]["fingerprint"] == filter_fingerprint(FILTER)
    assert body["rows"] == len(store.get_filtered(sid))

    narrowed = client.get(f"/api/sessions/{sid}/frame", params={"columns": "age,arm"})
    assert narrowed.status_code == 200, narrowed.text
    assert [c["name"] for c in narrowed.json()["columns"]] == ["age", "arm"]

    assert client.get("/api/sessions/no-such-session/frame").status_code == 404
    assert client.get(
        f"/api/sessions/{sid}/frame", params={"columns": "age,nope"}
    ).status_code == 422


# ── (d) a resident frame cannot outlive its filter ───────────────────────────

def test_run_refuses_a_frame_cut_under_a_different_filter():
    import ustat_engine
    from ustat_engine.spec import AnalysisSpec

    spec = AnalysisSpec(
        id="tests.frame_echo",
        fn=lambda frame, params: {"n": len(frame)},
        needs_frame=True,
        doc="test-only echo",
    )
    if spec.id not in ustat_engine.ANALYSES:
        ustat_engine.register(spec)

    df = pd.DataFrame({"a": [1.0, 2.0]})
    env = build_envelope(df, kinds={"a": "numeric"}, conditions=FILTER)
    frame = frame_from_envelope(env)

    # Same filter: runs.
    ok = ustat_engine.run(
        spec.id, frame, {"__filter_fingerprint": filter_fingerprint(FILTER)}
    )
    assert ok["n"] == len(frame)

    # No claim about the filter: also runs — the guard only fires on a claim.
    assert ustat_engine.run(spec.id, frame, {})["n"] == len(frame)

    with pytest.raises(EngineError) as exc:
        ustat_engine.run(spec.id, frame, {"__filter_fingerprint": filter_fingerprint([])})
    assert exc.value.status_hint == 409
    assert "Select Cases" in exc.value.message


def test_frame_from_envelope_rejects_a_foreign_schema():
    with pytest.raises(EngineError) as exc:
        frame_from_envelope({"schema": "something.else/9"})
    assert exc.value.status_hint == 422


# ── the filter move was behaviour-preserving at the mask level ───────────────

def test_apply_conditions_is_the_mask_applied():
    from ustat_engine.frame.select import apply_conditions, keep_mask

    df = pd.DataFrame({
        "n": [1, 2, 3, 4, 5],
        "s": ["a", "b", "", None, "b"],
    })
    for conditions in (
        [{"column": "n", "operator": "gte", "value": "3", "join": "AND"}],
        [{"column": "s", "operator": "missing", "join": "AND"}],
        [{"column": "s", "operator": "contains", "value": "b", "join": "AND"}],
        [
            {"column": "n", "operator": "lt", "value": "3", "join": "AND"},
            {"column": "s", "operator": "eq", "value": "b", "join": "OR"},
        ],
    ):
        mask = keep_mask(df, conditions)
        assert isinstance(mask, np.ndarray) and mask.dtype == bool
        assert len(mask) == len(df)
        assert_frame_equal(apply_conditions(df, conditions), df[mask])
